typography_spectrum: 0.15955955022946
color:
  brandStrength: 0.7961864727549255
  lightness: 0.04480638005770743
  saturation: 0.959523071302101
  rhythmicContrast: 0.1296669109724462
  brandColors:
    - '#9FA0A2'
    - '#2E3E4E'
    - '#000000'
    - '#CE8C00'
    - '#F9F100'
layout_spectrum: 0.6674583335407078
author:
  name: Chris Gadek
  email: chris@forgrowthmarketers.com
  url: 'https://www.linkedin.com/christophergadek'
name: For Growth Marketers
title: Content you can actually learn something from
description: Quality content. No bullshit.
